apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: devuser-developer-rolebinding
subjects:
      #first we have given user details
      - kind: User
        name: devuser
        apiGroup: rbac.authorization.k8s.io
roleRef:
      #secondly we will give role details      
        kind: Role
        name: developer
        apiGroup: rbac.authorization.k8s.io
        