apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-persistent-volume
spec:
    accessModes: 
       - ReadWriteOnce
    capacity:
         storage: 1Gi
    hostPath:
         path: /tmp/data
# and in production environment we dont use like this. 
#we use like this:
#awsElasticBlockStore:
     #volumeID: <volumne-id>
     #fsType: ext4                                