apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: my-replica-set
    labels:
       type: A
spec:
    template:
       metadata:
          name: myapp-pod
          labels:
             version: v1
       spec:
           containers:
               - name: nginx-container
                 image: nginx
    replicas: 1
    selector:
        matchLabels:
            version: v1             
