apiVersion: v1
kind: ReplicationController
metadata:
    name: my-replication-controller
    labels:
        type: A
spec:
    template:
       metadata:
          name: myapp-pod
          labels:
             version: v1
       spec:
           containers:
               - name: nginx-container
                 image: nginx   
    replicas: 1               

