apiVersion: v1
kind: Service
metadata:
     name: example-service
spec:
     type: LoadBalancer
     ports:
         - targetPort: 9376
           port: 8765
     selector:
        matchLables:
              app: example           